Repository Iccas-i/game_client, pull requests merged in 2023-08, with the labels that each got.

#72 [refactor]: Scene 파일과 script 파일 저장위치 분리 (#71)
  Iccas_game_front/Assets/Scripts.meta
  Iccas_game_front/Assets/Scripts/ArrowHandler.cs
  Iccas_game_front/Assets/Scripts/ArrowHandler.cs.meta
  Iccas_game_front/Assets/Scripts/ArrowHandler2.cs
  Iccas_game_front/Assets/Scripts/ArrowHandler2.cs.meta
  Iccas_game_front/Assets/Scripts/B_Move.cs
  Iccas_game_front/Assets/Scripts/B_Move.cs.meta
  Iccas_game_front/Assets/Scripts/Blue.prefab
  Iccas_game_front/Assets/Scripts/Blue.prefab.meta
  Iccas_game_front/Assets/Scripts/ButtonHandler.cs
  Iccas_game_front/Assets/Scripts/ButtonHandler.cs.meta
  Iccas_game_front/Assets/Scripts/CloseButtonHandler.cs
  Iccas_game_front/Assets/Scripts/CloseButtonHandler.cs.meta
  Iccas_game_front/Assets/Scripts/HealthReportPanelHandler.cs
  Iccas_game_front/Assets/Scripts/HealthReportPanelHandler.cs.meta
  Iccas_game_front/Assets/Scripts/HomePanelHandler.cs
  Iccas_game_front/Assets/Scripts/HomePanelHandler.cs.meta
  Iccas_game_front/Assets/Scripts/LoadScene.cs
  Iccas_game_front/Assets/Scripts/LoadScene.cs.meta
  Iccas_game_front/Assets/Scripts/Login.cs
  Iccas_game_front/Assets/Scripts/Login.cs.meta
  Iccas_game_front/Assets/Scripts/PanelHandler.cs
  Iccas_game_front/Assets/Scripts/PanelHandler.cs.meta
  Iccas_game_front/Assets/Scripts/PopDown.cs
  Iccas_game_front/Assets/Scripts/PopDown.cs.meta
  Iccas_game_front/Assets/Scripts/PopUp.cs
  Iccas_game_front/Assets/Scripts/PopUp.cs.meta
  Iccas_game_front/Assets/Scripts/PopUpShow.cs
  Iccas_game_front/Assets/Scripts/PopUpShow.cs.meta
  Iccas_game_front/Assets/Scripts/R_Move.cs
  Iccas_game_front/Assets/Scripts/R_Move.cs.meta
  Iccas_game_front/Assets/Scripts/ShopBtnHandler.cs
  Iccas_game_front/Assets/Scripts/ShopBtnHandler.cs.meta
  Iccas_game_front/Assets/Scripts/ShopCloseBtn.cs
  Iccas_game_front/Assets/Scripts/ShopCloseBtn.cs.meta
  Iccas_game_front/Assets/Scripts/ShopHandler.cs
  Iccas_game_front/Assets/Scripts/ShopHandler.cs.meta
  Iccas_game_front/Assets/Scripts/SignUp.cs
  Iccas_game_front/Assets/Scripts/SignUp.cs.meta
  Iccas_game_front/Assets/Scripts/Team_Challegne_Timer.cs
  Iccas_game_front/Assets/Scripts/Team_Challegne_Timer.cs.meta
  Iccas_game_front/Assets/Scripts/castle_tower_red(8).prefab
  Iccas_game_front/Assets/Scripts/castle_tower_red(8).prefab.meta
Labels: REFEATOR

#75 Design/74
  Iccas_game_front/Assets/Scenes/ArrowHandler2.cs
  Iccas_game_front/Assets/Scenes/ArrowHandler2.cs.meta
  Iccas_game_front/Assets/Scenes/Team_Indiv.unity
  Iccas_game_front/Assets/Scenes/Team_Map.unity
  Iccas_game_front/Assets/Scrtips.meta
  Iccas_game_front/Assets/Scrtips/ArrowHandler.cs
  Iccas_game_front/Assets/Scrtips/ArrowHandler.cs.meta
  Iccas_game_front/Assets/Scrtips/B_Move.cs
  Iccas_game_front/Assets/Scrtips/B_Move.cs.meta
  Iccas_game_front/Assets/Scrtips/Blue.prefab
  Iccas_game_front/Assets/Scrtips/Blue.prefab.meta
  Iccas_game_front/Assets/Scrtips/ButtonHandler.cs
  Iccas_game_front/Assets/Scrtips/ButtonHandler.cs.meta
  Iccas_game_front/Assets/Scrtips/CloseButtonHandler.cs
  Iccas_game_front/Assets/Scrtips/CloseButtonHandler.cs.meta
  Iccas_game_front/Assets/Scrtips/HealthReportPanelHandler.cs
  Iccas_game_front/Assets/Scrtips/HealthReportPanelHandler.cs.meta
  Iccas_game_front/Assets/Scrtips/HomePanelHandler.cs
  Iccas_game_front/Assets/Scrtips/HomePanelHandler.cs.meta
  Iccas_game_front/Assets/Scrtips/LoadScene.cs
  Iccas_game_front/Assets/Scrtips/LoadScene.cs.meta
  Iccas_game_front/Assets/Scrtips/Login.cs
  Iccas_game_front/Assets/Scrtips/Login.cs.meta
  Iccas_game_front/Assets/Scrtips/PanelHandler.cs
  Iccas_game_front/Assets/Scrtips/PanelHandler.cs.meta
  Iccas_game_front/Assets/Scrtips/PopDown.cs
  Iccas_game_front/Assets/Scrtips/PopDown.cs.meta
  Iccas_game_front/Assets/Scrtips/PopUp.cs
  Iccas_game_front/Assets/Scrtips/PopUp.cs.meta
  Iccas_game_front/Assets/Scrtips/PopUpShow.cs
  Iccas_game_front/Assets/Scrtips/PopUpShow.cs.meta
  Iccas_game_front/Assets/Scrtips/R_Move.cs
  Iccas_game_front/Assets/Scrtips/R_Move.cs.meta
  Iccas_game_front/Assets/Scrtips/ShopBtnHandler.cs
  Iccas_game_front/Assets/Scrtips/ShopBtnHandler.cs.meta
  Iccas_game_front/Assets/Scrtips/ShopCloseBtn.cs
  Iccas_game_front/Assets/Scrtips/ShopCloseBtn.cs.meta
  Iccas_game_front/Assets/Scrtips/ShopHandler.cs
  Iccas_game_front/Assets/Scrtips/ShopHandler.cs.meta
  Iccas_game_front/Assets/Scrtips/SignUp.cs
  Iccas_game_front/Assets/Scrtips/SignUp.cs.meta
  Iccas_game_front/Assets/Scrtips/Team_Challegne_Timer.cs
  Iccas_game_front/Assets/Scrtips/Team_Challegne_Timer.cs.meta
  Iccas_game_front/Assets/Scrtips/castle_tower_red(8).prefab
  Iccas_game_front/Assets/Scrtips/castle_tower_red(8).prefab.meta
  Iccas_game_front/Assets/Scrtips/playermovement.cs
  Iccas_game_front/Assets/Scrtips/playermovement.cs.meta
  Iccas_game_front/Assets/Scrtips/shooting.cs
  Iccas_game_front/Assets/Scrtips/shooting.cs.meta
  Iccas_game_front/Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
  Iccas_game_front/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Iccas_game_front/Assets/_Heathen Engineering/Assets/UX/HeathenEngineering.UX.asmdef
Labels: UX/UI

#77 [fix]: test (#76)
  Iccas_game_front/Assets/Scenes/Team_Indiv.unity
  Iccas_game_front/Assets/Yeeun/TeamResultResultAssets/Plazm 1.prefab
  Iccas_game_front/Assets/Yeeun/TeamResultResultAssets/Plazm 1.prefab.meta
Labels: 🔨FIX

#80 [feat]: Aws 접속하기 위한 ip 변경(#79)
  Iccas_game_front/Assets/Scrtips/HealthReportPanelHandler.cs
  Iccas_game_front/Assets/Scrtips/HomePanelHandler.cs
  Iccas_game_front/Assets/Scrtips/Login.cs
  Iccas_game_front/Assets/Scrtips/SignUp.cs
Labels: ⚙FEAT
